### ISSUE TITLE
seismic colormap

### ISSUE THREAD

**Issue by ponykid** [gatechzhu/SeisCM#1]
you know , there is also a 'seismic' colormap in the matplotlib , so the 'seismic colormap' in this programe is the same as the matplotlib?

**Comment by lijunzh** [comment]
@ponykid Thanks for your questions. Actually, it is different. You can compare the colormaps between matplotlib and this repo using the links below:

matplotlib colormaps: https://matplotlib.org/stable/gallery/color/colormap_reference.html
this repo: https://github.com/lijunzh/SeisCM#list-of-available-colormaps

More specifically, the perspective of the "seismic" colormap used in this repo is darker when the absolute value is smaller, which is exactly opposite in the matplotlib "seismic" colormap. This choice is not only more intuitive (magnitude corresponds to intensity), but also is widely adopted by many seismic literatures.

**Comment by ponykid** [comment]
Thank you for your reply, I have fully understood your answer.



At 2022-01-25 06:03:42, "Lijun Zhu" ***@***.***> wrote:

@ponykid Thanks for your questions. Actually, it is different. You can compare the colormaps between matplotlib and this repo using the links below:

matplotlib colormaps: https://matplotlib.org/stable/gallery/color/colormap_reference.html
this repo: https://github.com/lijunzh/SeisCM#list-of-available-colormaps

More specifically, the perspective of the "seismic" colormap used in this repo is darker when the absolute value is smaller, which is exactly opposite in the matplotlib "seismic" colormap. This choice is not only more intuitive (magnitude corresponds to intensity), but also is widely adopted by many seismic literatures.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
